### ISSUE TITLE
Help: Installing Linux kernel headers

### ISSUE THREAD

**Issue by ayushbindlish** [Locietta/xanmod-kernel-WSL2#26]
The kernel headers are missing. How can I get the kernel headers? And how do I install them? I know how to do it on Ubuntu but not too sure about wsl.

**Comment by Locietta** [comment]
Since we're using custom kernels on WSL, there's no corresponding `linux-headers-*` package on Debian or Ubuntu (this is the same situation for MS's official WSL2 kernel). AFAIK we have to build kernel from source and do `make headers_install` to get kernel headers installed. 

But I'm not sure whether enabling `CONFIG_IKHEADERS=y` is helpful (mentioned at microsoft/WSL#5526). I've attached a bzImage built with the option enabled, can you try it? 

👉 [bzImage.txt](https://github.com/Locietta/xanmod-kernel-WSL2/files/10526652/bzImage.txt) 
(github doesn't allow to upload files without extension, so I just add .txt)

**Comment by ayushbindlish** [comment]
Let me give it a try and I'll get back to you.

**Comment by ayushbindlish** [comment]
I am not too sure how to verify this.
A lot of packages are trying to access:
`linux-headers-6.1.8-locietta-WSL2-xanmod1`
@Locietta

**Comment by Nevuly** [comment]
@Locietta 

Can you check my gh-actions?

Maybe It will help to resolve this issue.

My gh-actions includes compressing and distributing kernel header and kernel module together.

https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling/blob/wsl-6.7-rolling/.github/workflows/build.yml
